# Generated by Django 3.2 on 2021-04-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='category',
            new_name='customer',
        ),
    ]
